/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/

#include <rpi_libcamera_driver.h>

using namespace unit::rpi_libcamera_driver;


OnCameraImage::Output rpi_libcamera_driver::OnCameraImage(const OnCameraImage::Input& input) {
    static_assert(false, "Implement me");
}
