/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/

#include <yuyv_to_rgb.h>

using namespace unit::yuyv_to_rgb;


OnYUYV::Output yuyv_to_rgb::OnYUYV(const OnYUYV::Input& input) {
    static_assert(false, "Implement me");
}
