/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/

#include <resnet_demo.h>

using namespace unit::resnet_demo;


OnRGB::Output resnet_demo::OnRGB(const OnRGB::Input& input) {
    static_assert(false, "Implement me");
}
