/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/
#include <unit/resnet_demo/unit_base.h>

class resnet_demo : public unit::resnet_demo::Base {
public:
  resnet_demo(std::optional<std::string> name_override = {}) 
  : unit::resnet_demo::Base(name_override)
  {}


  virtual unit::resnet_demo::OnRGB::Output
  OnRGB(const unit::resnet_demo::OnRGB::Input &input) override;

};