/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/

#include <rpi_freenove_mecanum_driver.h>

using namespace unit::rpi_freenove_mecanum_driver;


Update::Output rpi_freenove_mecanum_driver::Update(const Update::Input& input) {
    static_assert(false, "Implement me");
}
