/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/

#include <joystick_driver.h>

using namespace unit::joystick_driver;


Tick::Output joystick_driver::Tick(const Tick::Input& input) {
    static_assert(false, "Implement me");
}
