/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/
#include <unit/joystick_driver/unit_base.h>

class joystick_driver : public unit::joystick_driver::Base {
public:
  joystick_driver(const Args& args, const std::optional<std::string_view>& name_override = {}) 
  : unit::joystick_driver::Base(args, name_override)
  {}


  virtual unit::joystick_driver::Tick::Output
  Tick(const unit::joystick_driver::Tick::Input &input) override;

};