/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/

#include <v4l2_camera_driver.h>

using namespace unit::v4l2_camera_driver;


OnCameraImage::Output v4l2_camera_driver::OnCameraImage(const OnCameraImage::Input& input) {
    static_assert(false, "Implement me");
}
