/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/
#include <unit/v4l2_camera_driver/unit_base.h>

class v4l2_camera_driver : public unit::v4l2_camera_driver::Base {
public:
  v4l2_camera_driver(std::optional<std::string> name_override = {}) 
  : unit::v4l2_camera_driver::Base(name_override)
  {}


  virtual unit::v4l2_camera_driver::OnCameraImage::Output
  OnCameraImage(const unit::v4l2_camera_driver::OnCameraImage::Input &input) override;

};