/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/

#include <static_transform_publisher.h>

using namespace unit::static_transform_publisher;


Publish::Output static_transform_publisher::Publish(const Publish::Input& input) {
    static_assert(false, "Implement me");
}
