/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/

#include <rplidar_driver.h>

using namespace unit::rplidar_driver;


OnLidar::Output rplidar_driver::OnLidar(const OnLidar::Input& input) {
    static_assert(false, "Implement me");
}
