/*

  DO NOT EDIT THIS FILE

  This is a template for use with your Unit, to use as a base, provided as an example.

*/
#include <unit/perception_demo/unit_base.h>

class perception_demo : public unit::perception_demo::Base {
public:
  perception_demo(const Args& args, const std::optional<std::string_view>& name_override = {}) 
  : unit::perception_demo::Base(args, name_override)
  {}


  virtual unit::perception_demo::OnRGB::Output
  OnRGB(const unit::perception_demo::OnRGB::Input &input) override;

};